### ISSUE TITLE
pulling the vulnerability scan report not working

### ISSUE THREAD

**Issue by mahadev21** [ruzickap/k8s-knative-gitlab-harbor#27]
I tried to download the scan report but its not working, any idea how to do it?

curl -u "aduser06:admin" --header "Content-Type: application/json" -X GET "https://harbor.${MY_DOMAIN}/api/repositories/my_project%2Fnginx/tags/1.13.12/scan"

**Comment by ruzickap** [comment]
Please try to ask the people in harbor project slack / mailing list.
I didn't do it myself...
